export const ADD_LIST = 'LISTS/ADD_LIST';
export const EDIT_LIST = 'LISTS/EDIT_LIST';
export const DELETE_LIST = 'LISTS/DELETE_LIST';
export const SHOW_SPINNER = 'LISTS/SHOW_SPINNER';
export const LISTS_DATA_RECIEVED = 'LISTS/LISTS_DATA_RECIEVED';
export const SWITCH_LIST = 'LISTS/SWITCH_LIST';
